# Generated by Django 6.0.5 on 2026-05-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(default='router', max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded')], default='ONLINE', max_length=20)),
                ('ssh_port', models.IntegerField(default=22)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RLPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('policy_data', models.JSONField()),
                ('performance_score', models.FloatField(default=0.0)),
                ('training_episodes', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(choices=[('SERVICE_CRASH', 'Service Crash'), ('LINK_FAILURE', 'Link Failure'), ('DDOS_ATTACK', 'DDoS Attack'), ('PERFORMANCE_DEGRADATION', 'Performance Degradation'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('DIAGNOSING', 'Diagnosing'), ('READY_FOR_ACTION', 'Ready for Action'), ('MANUAL_REVIEW', 'Manual Review'), ('HEALING', 'Healing'), ('HEALED', 'Healed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='DETECTED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.device')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='HealingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('RESTART_SERVICE', 'Restart Service'), ('REROUTE_TRAFFIC', 'Reroute Traffic'), ('BLOCK_SOURCE_IP', 'Block Source IP'), ('REBOOT_DEVICE', 'Reboot Device'), ('CLEAR_CACHE', 'Clear Cache'), ('RATE_LIMIT', 'Rate Limit'), ('CUSTOM', 'Custom')], max_length=30)),
                ('command', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating in Sandbox'), ('EXECUTING', 'Executing'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='PENDING', max_length=20)),
                ('sandbox_result', models.CharField(blank=True, max_length=20)),
                ('execution_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healing_actions', to='monitoring.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RLReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_value', models.IntegerField(choices=[(1, 'Success'), (-1, 'Failure')])),
                ('state_context', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('healing_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='monitoring.healingaction')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('packet_loss', models.FloatField(blank=True, null=True)),
                ('bandwidth_util', models.FloatField(blank=True, null=True)),
                ('interface_status', models.JSONField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='monitoring.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='telemetry_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.telemetry'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['-timestamp'], name='monitoring__timesta_6daf6a_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['device', '-timestamp'], name='monitoring__device__3d9fbe_idx'),
        ),
    ]
