# Generated by Django 6.0.5 on 2026-05-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('cisco_ios', 'Cisco IOS'), ('mikrotik_routeros', 'MikroTik RouterOS'), ('juniper_junos', 'Juniper JunOS'), ('huawei_vrp', 'Huawei VRP'), ('generic', 'Generic/Mock Router')], default='generic', max_length=50),
        ),
    ]
